"""
Centralized mock data for U Kost.
All kost data, user data, and other mock data used across the application.
This module will be replaced with actual database queries in production.
"""

MOCK_KOST_DATA = [
    {
        'id': 1,
        'name': 'Kost Pondok Mahasiswa Bahagia',
        'address': 'Jl. Taman Apel No. 14, Tanjung Duren, Jakarta Barat',
        'price': 1300000,
        'price_display': 'Rp1.300.000',
        'deposit': 500000,
        'deposit_display': 'Rp500.000',
        'distance': 1.2,
        'rating': 4.8,
        'room_type': 'Putra',
        'room_size': '3m x 4m',
        'availability': 3,
        'wifi': True,
        'wifi_speed': '50 Mbps',
        'bathroom': True,
        'furnished': True,
        'ac': True,
        'parking': True,
        'security': True,
        'cctv': True,
        'kitchen': True,
        'laundry': True,
        'electricity_included': True,
        'access_24h': True,
        'window': True,
        'facilities': ['Wi-Fi 50 Mbps', 'Kamar Mandi Dalam', 'AC', 'CCTV', 'Parkir Motor', 'Dapur Bersama', 'Laundry', 'Security 24 Jam', 'Furnitur Lengkap', 'Listrik Termasuk'],
        'images': ['kost1_1.jpg', 'kost1_2.jpg', 'kost1_3.jpg', 'kost1_4.jpg'],
        'score': 94,
        'scores': {
            'harga': 96,
            'jarak': 94,
            'fasilitas': 92,
            'keamanan': 95,
            'rating': 93,
        },
        'rank': 1,
        'description': 'Kost nyaman dengan fasilitas lengkap, cocok untuk mahasiswa yang mencari tempat tinggal dekat kampus dengan harga terjangkau.',
        'owner_name': 'Bpk. Hendra Wijaya',
        'owner_phone': '0812-3456-7890',
        'rules': ['Tidak boleh membawa hewan peliharaan', 'Jam malam pukul 23:00', 'Tamu lawan jenis di ruang tamu'],
    },
    {
        'id': 2,
        'name': 'Kost Griya Asri Kampus',
        'address': 'Jl. Kedoya Raya No. 27, Kedoya, Jakarta Barat',
        'price': 1500000,
        'price_display': 'Rp1.500.000',
        'deposit': 750000,
        'deposit_display': 'Rp750.000',
        'distance': 1.8,
        'rating': 4.6,
        'room_type': 'Campur',
        'room_size': '3m x 3.5m',
        'availability': 5,
        'wifi': True,
        'wifi_speed': '30 Mbps',
        'bathroom': True,
        'furnished': True,
        'ac': True,
        'parking': True,
        'security': True,
        'cctv': True,
        'kitchen': False,
        'laundry': True,
        'electricity_included': False,
        'access_24h': True,
        'window': True,
        'facilities': ['Wi-Fi 30 Mbps', 'Kamar Mandi Dalam', 'AC', 'CCTV', 'Parkir Motor & Mobil', 'Laundry', 'Security 24 Jam', 'Furnitur Lengkap'],
        'images': ['kost2_1.jpg', 'kost2_2.jpg', 'kost2_3.jpg'],
        'score': 89,
        'scores': {
            'harga': 88,
            'jarak': 90,
            'fasilitas': 90,
            'keamanan': 92,
            'rating': 85,
        },
        'rank': 2,
        'description': 'Kost modern dengan desain minimalis, lokasi strategis dekat kampus UKRIDA Kedoya.',
        'owner_name': 'Ibu Sari Dewi',
        'owner_phone': '0813-9876-5432',
        'rules': ['Tidak boleh merokok di kamar', 'Jam malam pukul 22:00', 'Bayar sewa di muka'],
    },
    {
        'id': 3,
        'name': 'Kost Melati Indah',
        'address': 'Jl. Melati No. 8, Tanjung Duren Utara, Jakarta Barat',
        'price': 1100000,
        'price_display': 'Rp1.100.000',
        'deposit': 500000,
        'deposit_display': 'Rp500.000',
        'distance': 2.1,
        'rating': 4.5,
        'room_type': 'Putri',
        'room_size': '3m x 3m',
        'availability': 2,
        'wifi': True,
        'wifi_speed': '20 Mbps',
        'bathroom': True,
        'furnished': True,
        'ac': False,
        'parking': True,
        'security': True,
        'cctv': True,
        'kitchen': True,
        'laundry': False,
        'electricity_included': True,
        'access_24h': False,
        'window': True,
        'facilities': ['Wi-Fi 20 Mbps', 'Kamar Mandi Dalam', 'CCTV', 'Parkir Motor', 'Dapur Bersama', 'Security 24 Jam', 'Furnitur Lengkap', 'Listrik Termasuk'],
        'images': ['kost3_1.jpg', 'kost3_2.jpg', 'kost3_3.jpg'],
        'score': 84,
        'scores': {
            'harga': 92,
            'jarak': 82,
            'fasilitas': 78,
            'keamanan': 88,
            'rating': 80,
        },
        'rank': 3,
        'description': 'Kost khusus putri dengan suasana tenang dan aman, cocok untuk mahasiswi UKRIDA.',
        'owner_name': 'Ibu Melati',
        'owner_phone': '0815-1234-5678',
        'rules': ['Khusus putri', 'Jam malam pukul 22:00', 'Tidak boleh masak di kamar'],
    },
    {
        'id': 4,
        'name': 'Kost Graha Mulia',
        'address': 'Jl. Duri Kepa No. 52, Duri Kepa, Jakarta Barat',
        'price': 1800000,
        'price_display': 'Rp1.800.000',
        'deposit': 1000000,
        'deposit_display': 'Rp1.000.000',
        'distance': 0.8,
        'rating': 4.9,
        'room_type': 'Campur',
        'room_size': '4m x 4m',
        'availability': 1,
        'wifi': True,
        'wifi_speed': '100 Mbps',
        'bathroom': True,
        'furnished': True,
        'ac': True,
        'parking': True,
        'security': True,
        'cctv': True,
        'kitchen': True,
        'laundry': True,
        'electricity_included': True,
        'access_24h': True,
        'window': True,
        'facilities': ['Wi-Fi 100 Mbps', 'Kamar Mandi Dalam', 'AC', 'CCTV', 'Parkir Motor & Mobil', 'Dapur Bersama', 'Laundry', 'Security 24 Jam', 'Furnitur Lengkap', 'Listrik Termasuk', 'Akses 24 Jam', 'Jendela Luar'],
        'images': ['kost4_1.jpg', 'kost4_2.jpg', 'kost4_3.jpg', 'kost4_4.jpg'],
        'score': 91,
        'scores': {
            'harga': 78,
            'jarak': 98,
            'fasilitas': 98,
            'keamanan': 96,
            'rating': 95,
        },
        'rank': 4,
        'description': 'Kost premium dengan fasilitas lengkap dan lokasi sangat dekat dengan kampus UKRIDA.',
        'owner_name': 'Bpk. Mulia Santoso',
        'owner_phone': '0816-7890-1234',
        'rules': ['Deposit 1 bulan', 'Bayar tepat waktu', 'Jaga kebersihan bersama'],
    },
    {
        'id': 5,
        'name': "Kost D'Green Campus",
        'address': 'Jl. Tanjung Duren Barat No. 33, Jakarta Barat',
        'price': 1400000,
        'price_display': 'Rp1.400.000',
        'deposit': 700000,
        'deposit_display': 'Rp700.000',
        'distance': 1.5,
        'rating': 4.7,
        'room_type': 'Putra',
        'room_size': '3m x 3.5m',
        'availability': 4,
        'wifi': True,
        'wifi_speed': '40 Mbps',
        'bathroom': True,
        'furnished': True,
        'ac': True,
        'parking': True,
        'security': True,
        'cctv': False,
        'kitchen': True,
        'laundry': True,
        'electricity_included': False,
        'access_24h': True,
        'window': True,
        'facilities': ['Wi-Fi 40 Mbps', 'Kamar Mandi Dalam', 'AC', 'Parkir Motor', 'Dapur Bersama', 'Laundry', 'Furnitur Lengkap', 'Akses 24 Jam'],
        'images': ['kost5_1.jpg', 'kost5_2.jpg', 'kost5_3.jpg'],
        'score': 87,
        'scores': {
            'harga': 90,
            'jarak': 88,
            'fasilitas': 85,
            'keamanan': 82,
            'rating': 90,
        },
        'rank': 5,
        'description': 'Kost bernuansa hijau dengan taman kecil, suasana asri dekat kampus.',
        'owner_name': 'Bpk. Green',
        'owner_phone': '0817-5678-9012',
        'rules': ['Tidak boleh membawa hewan', 'Jaga ketenangan setelah jam 22:00'],
    },
    {
        'id': 6,
        'name': 'Kost Melati Asri',
        'address': 'Jl. Arjuna Utara No. 19, Duri Kepa, Jakarta Barat',
        'price': 950000,
        'price_display': 'Rp950.000',
        'deposit': 400000,
        'deposit_display': 'Rp400.000',
        'distance': 2.5,
        'rating': 4.3,
        'room_type': 'Putri',
        'room_size': '2.5m x 3m',
        'availability': 6,
        'wifi': True,
        'wifi_speed': '15 Mbps',
        'bathroom': False,
        'furnished': True,
        'ac': False,
        'parking': True,
        'security': True,
        'cctv': False,
        'kitchen': True,
        'laundry': False,
        'electricity_included': True,
        'access_24h': False,
        'window': True,
        'facilities': ['Wi-Fi 15 Mbps', 'Parkir Motor', 'Dapur Bersama', 'Security 24 Jam', 'Furnitur Lengkap', 'Listrik Termasuk'],
        'images': ['kost6_1.jpg', 'kost6_2.jpg'],
        'score': 76,
        'scores': {
            'harga': 95,
            'jarak': 72,
            'fasilitas': 65,
            'keamanan': 75,
            'rating': 73,
        },
        'rank': 6,
        'description': 'Kost ekonomis untuk mahasiswi yang mengutamakan harga terjangkau.',
        'owner_name': 'Ibu Asri',
        'owner_phone': '0818-2345-6789',
        'rules': ['Khusus putri', 'Jam malam pukul 21:30', 'Tidak boleh masak di kamar'],
    },
    {
        'id': 7,
        'name': 'Kost Harmoni Residence',
        'address': 'Jl. Kembangan Raya No. 45, Kembangan, Jakarta Barat',
        'price': 2000000,
        'price_display': 'Rp2.000.000',
        'deposit': 1000000,
        'deposit_display': 'Rp1.000.000',
        'distance': 3.2,
        'rating': 4.7,
        'room_type': 'Campur',
        'room_size': '4m x 5m',
        'availability': 2,
        'wifi': True,
        'wifi_speed': '100 Mbps',
        'bathroom': True,
        'furnished': True,
        'ac': True,
        'parking': True,
        'security': True,
        'cctv': True,
        'kitchen': True,
        'laundry': True,
        'electricity_included': True,
        'access_24h': True,
        'window': True,
        'facilities': ['Wi-Fi 100 Mbps', 'Kamar Mandi Dalam', 'AC', 'CCTV', 'Parkir Motor & Mobil', 'Dapur Bersama', 'Laundry', 'Security 24 Jam', 'Furnitur Lengkap', 'Listrik Termasuk', 'Akses 24 Jam', 'Jendela Luar'],
        'images': ['kost7_1.jpg', 'kost7_2.jpg', 'kost7_3.jpg'],
        'score': 82,
        'scores': {
            'harga': 70,
            'jarak': 75,
            'fasilitas': 98,
            'keamanan': 95,
            'rating': 90,
        },
        'rank': 7,
        'description': 'Kost premium dengan fasilitas mewah, cocok untuk mahasiswa yang mengutamakan kenyamanan.',
        'owner_name': 'Bpk. Harmoni',
        'owner_phone': '0819-8765-4321',
        'rules': ['Deposit 1 bulan', 'Tidak boleh merokok'],
    },
    {
        'id': 8,
        'name': 'Kost Cendana Residence',
        'address': 'Jl. Cendana No. 12, Tanjung Duren Selatan, Jakarta Barat',
        'price': 1200000,
        'price_display': 'Rp1.200.000',
        'deposit': 600000,
        'deposit_display': 'Rp600.000',
        'distance': 1.0,
        'rating': 4.4,
        'room_type': 'Putra',
        'room_size': '3m x 3m',
        'availability': 3,
        'wifi': True,
        'wifi_speed': '25 Mbps',
        'bathroom': True,
        'furnished': True,
        'ac': False,
        'parking': True,
        'security': True,
        'cctv': True,
        'kitchen': False,
        'laundry': True,
        'electricity_included': False,
        'access_24h': True,
        'window': False,
        'facilities': ['Wi-Fi 25 Mbps', 'Kamar Mandi Dalam', 'CCTV', 'Parkir Motor', 'Laundry', 'Security 24 Jam', 'Furnitur Lengkap', 'Akses 24 Jam'],
        'images': ['kost8_1.jpg', 'kost8_2.jpg', 'kost8_3.jpg'],
        'score': 80,
        'scores': {
            'harga': 90,
            'jarak': 92,
            'fasilitas': 72,
            'keamanan': 85,
            'rating': 78,
        },
        'rank': 8,
        'description': 'Kost strategis dekat kampus dengan harga bersahabat.',
        'owner_name': 'Bpk. Cendana',
        'owner_phone': '0821-3456-7890',
        'rules': ['Bayar sewa tanggal 1', 'Jaga ketenangan'],
    },
]

# Mapping campus data
CAMPUS_DATA = [
    {'id': 1, 'name': 'Universitas Kristen Krida Wacana - Kampus 1 Tanjung Duren', 'short': 'UKRIDA Kampus 1'},
    {'id': 2, 'name': 'Universitas Kristen Krida Wacana - Kampus 2 Kedoya', 'short': 'UKRIDA Kampus 2'},
]

FAKULTAS_DATA = [
    'Fakultas Kedokteran',
    'Fakultas Kedokteran Gigi',
    'Fakultas Teknik & Ilmu Komputer',
    'Fakultas Ekonomi & Bisnis',
    'Fakultas Ilmu Sosial & Humaniora',
    'Fakultas Psikologi',
]

# Facilities list for the preference form
FACILITIES_LIST = [
    {'id': 'wifi', 'name': 'Wi-Fi Cepat', 'icon': 'fas fa-wifi'},
    {'id': 'bathroom', 'name': 'KM Dalam', 'icon': 'fas fa-bath'},
    {'id': 'furnished', 'name': 'Furnitur', 'icon': 'fas fa-couch'},
    {'id': 'bed', 'name': 'Kasur', 'icon': 'fas fa-bed'},
    {'id': 'ac', 'name': 'AC', 'icon': 'fas fa-snowflake'},
    {'id': 'parking', 'name': 'Parkir', 'icon': 'fas fa-car'},
    {'id': 'security', 'name': 'Security 24 Jam', 'icon': 'fas fa-shield-alt'},
    {'id': 'cctv', 'name': 'CCTV', 'icon': 'fas fa-video'},
    {'id': 'area', 'name': 'Kawasan', 'icon': 'fas fa-map-marker-alt'},
    {'id': 'kitchen', 'name': 'Dapur Bersama', 'icon': 'fas fa-utensils'},
    {'id': 'laundry', 'name': 'Laundry', 'icon': 'fas fa-tshirt'},
    {'id': 'electricity', 'name': 'Listrik Termasuk', 'icon': 'fas fa-bolt'},
    {'id': 'access_24h', 'name': 'Akses 24 Jam', 'icon': 'fas fa-clock'},
    {'id': 'window', 'name': 'Jendela Luar', 'icon': 'fas fa-window-maximize'},
]

# Priority criteria
PRIORITY_CRITERIA = [
    {'id': 'harga', 'name': 'Harga Sewa', 'icon': 'fas fa-money-bill-wave', 'description': 'Kesesuaian harga dengan budget yang ditentukan'},
    {'id': 'jarak', 'name': 'Jarak ke Kampus', 'icon': 'fas fa-route', 'description': 'Kedekatan lokasi kost dengan kampus'},
    {'id': 'fasilitas', 'name': 'Kelengkapan Fasilitas', 'icon': 'fas fa-th-list', 'description': 'Ketersediaan fasilitas yang dibutuhkan'},
    {'id': 'keamanan', 'name': 'Keamanan Lingkungan', 'icon': 'fas fa-shield-alt', 'description': 'Tingkat keamanan di sekitar kost'},
    {'id': 'kenyamanan', 'name': 'Kebersihan & Kenyamanan', 'icon': 'fas fa-star', 'description': 'Kondisi kebersihan dan kenyamanan kost'},
]

# Mock search history
MOCK_HISTORY = [
    {
        'id': 1,
        'date': '28 September 2026',
        'time': '14:30',
        'campus': 'UKRIDA Kampus 1',
        'budget': 'Rp1.500.000',
        'distance': '3.0 km',
        'priority': 'Harga & Jarak',
        'result_count': 5,
        'status': 'completed',
    },
    {
        'id': 2,
        'date': '25 September 2026',
        'time': '09:15',
        'campus': 'UKRIDA Kampus 2',
        'budget': 'Rp2.000.000',
        'distance': '5.0 km',
        'priority': 'Fasilitas & Keamanan',
        'result_count': 8,
        'status': 'completed',
    },
    {
        'id': 3,
        'date': '20 September 2026',
        'time': '16:45',
        'campus': 'UKRIDA Kampus 1',
        'budget': 'Rp1.000.000',
        'distance': '2.0 km',
        'priority': 'Harga',
        'result_count': 3,
        'status': 'completed',
    },
]


def get_kost_by_id(kost_id):
    """Get a single kost by ID."""
    for kost in MOCK_KOST_DATA:
        if kost['id'] == kost_id:
            return kost
    return None


def get_all_kost():
    """Get all kost data."""
    return MOCK_KOST_DATA


def get_recommended_kost(limit=5):
    """Get top recommended kost sorted by score."""
    sorted_kost = sorted(MOCK_KOST_DATA, key=lambda x: x['score'], reverse=True)
    return sorted_kost[:limit]


def get_kost_for_landing():
    """Get 3 kost for landing page preview."""
    return get_recommended_kost(3)
