# Generated by Django 6.1.2 on 2026-10-08 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type', models.CharField(choices=[('Campur', 'Campur'), ('Putra', 'Putra'), ('Putri', 'Putri')], default='Campur', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('address_details', models.CharField(max_length=355)),
                ('price', models.IntegerField()),
                ('distance_to_campus_1', models.IntegerField()),
                ('distance_to_campus_2', models.IntegerField()),
                ('waiting_list', models.BooleanField(default=False)),
                ('no_deposit_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('address_detail', models.CharField(max_length=355)),
            ],
        ),
        migrations.CreateModel(
            name='KostPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=255)),
                ('is_first_month_promo', models.BooleanField(default=False)),
                ('first_month_discount', models.IntegerField(default=0, help_text='Potongan harga pada bulan pertama')),
                ('other_promo_label', models.CharField(blank=True, max_length=255, null=True)),
                ('has_long_term_promo', models.BooleanField(default=False)),
                ('long_term_promo_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('long_term_savings_amount', models.IntegerField(default=0, help_text='Jumlah penghematan sewa jangka panjang')),
                ('kost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='ukost.kost')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_limit', models.IntegerField()),
                ('radius_limit', models.IntegerField()),
                ('facility', models.JSONField()),
                ('criteria_weight', models.JSONField()),
                ('search_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='ukost.university')),
            ],
            options={
                'verbose_name_plural': 'Histories',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL)),
                ('kost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ukost.kost')),
            ],
            options={
                'unique_together': {('user', 'kost')},
            },
        ),
        migrations.CreateModel(
            name='KostFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_kosts', to='ukost.facility')),
                ('kost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kost_facilities', to='ukost.kost')),
            ],
            options={
                'unique_together': {('kost', 'facility')},
            },
        ),
    ]
