# Generated by Django 6.1.2 on 2026-10-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukost', '0002_faculty_studyprogram_userdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='kostfacility',
            options={'verbose_name_plural': 'Kost Facilities'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='kost',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
